package top.duwd.common.domain.sub.entity;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

@Table(name = "t_sub_question")
public class SubQuestion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_question.id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_question.user_id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_question.question_id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    private Integer questionId;

    private String questionTitle;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_question.valid
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_question.create_time
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_question.update_time
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sub_question
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_question.id
     *
     * @return the value of t_sub_question.id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_question.id
     *
     * @param id the value for t_sub_question.id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_question.user_id
     *
     * @return the value of t_sub_question.user_id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_question.user_id
     *
     * @param userId the value for t_sub_question.user_id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_question.question_id
     *
     * @return the value of t_sub_question.question_id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_question.question_id
     *
     * @param questionId the value for t_sub_question.question_id
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_question.valid
     *
     * @return the value of t_sub_question.valid
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_question.valid
     *
     * @param valid the value for t_sub_question.valid
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_question.create_time
     *
     * @return the value of t_sub_question.create_time
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_question.create_time
     *
     * @param createTime the value for t_sub_question.create_time
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_question.update_time
     *
     * @return the value of t_sub_question.update_time
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_question.update_time
     *
     * @param updateTime the value for t_sub_question.update_time
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_question
     *
     * @mbggenerated Tue May 05 11:48:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", questionId=").append(questionId);
        sb.append(", questionTitle=").append(questionTitle);
        sb.append(", valid=").append(valid);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    public String getQuestionTitle() {
        return questionTitle;
    }

    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
    }
}